---@class Job_bodygroup
---@field [string] integer[]

---@class DarkRP_job_create
---@field color Gmod_color
---@field model string[]
---@field weapons string[]
---@field description string
---@field command string
---@field max integer
---@field salary integer
---@field admin integer
---@field vote boolean
---@field hasLicense boolean | nil
---@field category string
---@field sub_category nil | string
---@field candemote boolean
---@field medic boolean | nil
---@field model_zombie nil | string
---@field level integer
---@field bodygroups Job_bodygroup[] | nil
---@field PlayerSpawn nil | function
---@field PlayerLoadout nil | function
---@field PlayerCanPickupWeapon nil | function

---@class DarkRP_job : DarkRP_job_create
---@field name string
